apiVersion: v1
metadata:
  name: devise-postgresql-db-svc
kind: Service
spec:
  ports:
    - name: devise-postgresql-db-svc
      protocol: TCP
      port: 18000
      targetPort: 5432
  type: NodePort
  selector:
    name: devise-postgresql-db
