version: '3'
services:
  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_PASSWORD=developer
      - POSTGRES_USER=developer
      - POSTGRES_DB=devise_postgresql_development
    ports:
      - 5432:5432
