services:
  db:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: developer
      POSTGRES_USER: developer

  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
